-- ============================================================
-- SHIPMENT table audit logging
-- Sequence and log table (reference, already exists in database)
-- ============================================================

-- CREATE SEQUENCE DISTRIB.SHIPMENT_LOGSQ
--   MINVALUE 1
--   MAXVALUE 9999999999999999999999999999
--   INCREMENT BY 1
--   START WITH 241763759
--   CACHE 20
--   NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

-- CREATE TABLE DISTRIB.SHIPMENT_LOG
--    (
--     ID                   NUMBER(10,0)   NOT NULL ENABLE,
--     ACTION               VARCHAR2(1 BYTE),
--     HAPPENED_AT          DATE,
-- 	SHIPMENTID           NOT NULL VARCHAR2(20),
-- 	CCODE_SENDER         NUMBER(10),
-- 	TMP                  VARCHAR2(1),
-- 	LORRYID              NUMBER(10),
-- 	NRDOLLIES            NUMBER(10),
-- 	NRCRATES             NUMBER(10),
-- 	EXPECTED_DEPARTURE   DATE,
-- 	DEPARTURE            DATE,
-- 	EXPECTED_ARRIVAL     DATE,
-- 	ARRIVAL              DATE,
-- 	HASARRIVED           VARCHAR2(1),
-- 	HASBEENBOOKEDIN      VARCHAR2(1),
-- 	CLOSED               VARCHAR2(1),
-- 	CCODE_RECEIVER       NUMBER(10),
-- 	LICENSEPLATE         VARCHAR2(20),
-- 	SHIPMENTTYPE         NUMBER(10),
-- 	PRINTED              VARCHAR2(1),
-- 	CUSTNO               VARCHAR2(16),
-- 	SHIPDATE             VARCHAR2(8),
-- 	EXPORTED             VARCHAR2(1),
-- 	WSRECEIVING          NUMBER(10),
-- 	DISRECEIVING         VARCHAR2(1),
-- 	DMSCANNING           VARCHAR2(1),
-- 	SENDERDESCRIPTION    VARCHAR2(40),
-- 	LOCATIONID           NUMBER(10),
-- 	LOCATIONAREAID       NUMBER(10),
-- 	STAGEDSINCE          DATE,
-- 	HASBEENCOPIED        VARCHAR2(1),
-- 	VENDORCODE           VARCHAR2(10),
-- 	CHANGED              DATE,
-- 	DMPROCESSED          NOT NULL VARCHAR2(1),
-- 	XDOCKTOUCHED         VARCHAR2(1),
-- 	MANDATORYPRINTING    VARCHAR2(1),
--     CONSTRAINT SHIPMENT_LOG_PK PRIMARY KEY (ID)
-- );

-- ============================================================
-- TRIGGER 1: BEFORE INSERT (existing)
-- ============================================================
CREATE OR REPLACE TRIGGER DISTRIB.SHIPMENT_LOG1
  BEFORE INSERT ON DISTRIB.SHIPMENT
  FOR EACH ROW
BEGIN
  INSERT INTO SHIPMENT_LOG
    (ID, HAPPENED_AT, ACTION,
	SHIPMENTID, CCODE_SENDER, TMP, LORRYID, NRDOLLIES, NRCRATES, EXPECTED_DEPARTURE,
	DEPARTURE, EXPECTED_ARRIVAL, ARRIVAL, HASARRIVED, HASBEENBOOKEDIN, CLOSED,
	CCODE_RECEIVER, LICENSEPLATE, SHIPMENTTYPE, PRINTED, CUSTNO, SHIPDATE, EXPORTED, WSRECEIVING, DISRECEIVING,
	DMSCANNING, SENDERDESCRIPTION, LOCATIONID, LOCATIONAREAID, STAGEDSINCE, HASBEENCOPIED, VENDORCODE,
	CHANGED, DMPROCESSED, XDOCKTOUCHED, MANDATORYPRINTING)
  VALUES
    (SHIPMENT_LOGSQ.NEXTVAL, SYSTIMESTAMP, 'I',
	:NEW.SHIPMENTID, :NEW.CCODE_SENDER, :NEW.TMP, :NEW.LORRYID, :NEW.NRDOLLIES, :NEW.NRCRATES, :NEW.EXPECTED_DEPARTURE,
	:NEW.DEPARTURE, :NEW.EXPECTED_ARRIVAL, :NEW.ARRIVAL, :NEW.HASARRIVED, :NEW.HASBEENBOOKEDIN, :NEW.CLOSED,
	:NEW.CCODE_RECEIVER, :NEW.LICENSEPLATE, :NEW.SHIPMENTTYPE, :NEW.PRINTED, :NEW.CUSTNO, :NEW.SHIPDATE, :NEW.EXPORTED, :NEW.WSRECEIVING, :NEW.DISRECEIVING,
	:NEW.DMSCANNING, :NEW.SENDERDESCRIPTION, :NEW.LOCATIONID, :NEW.LOCATIONAREAID, :NEW.STAGEDSINCE, :NEW.HASBEENCOPIED, :NEW.VENDORCODE,
	:NEW.CHANGED, :NEW.DMPROCESSED, :NEW.XDOCKTOUCHED, :NEW.MANDATORYPRINTING);
END SHIPMENT_LOG1;
/
ALTER TRIGGER DISTRIB.SHIPMENT_LOG1 ENABLE;

-- ============================================================
-- TRIGGER 2: BEFORE UPDATE
-- ============================================================
CREATE OR REPLACE TRIGGER DISTRIB.SHIPMENT_LOG2
  BEFORE UPDATE ON DISTRIB.SHIPMENT
  FOR EACH ROW
BEGIN
  INSERT INTO SHIPMENT_LOG
    (ID, HAPPENED_AT, ACTION,
	SHIPMENTID, CCODE_SENDER, TMP, LORRYID, NRDOLLIES, NRCRATES, EXPECTED_DEPARTURE,
	DEPARTURE, EXPECTED_ARRIVAL, ARRIVAL, HASARRIVED, HASBEENBOOKEDIN, CLOSED,
	CCODE_RECEIVER, LICENSEPLATE, SHIPMENTTYPE, PRINTED, CUSTNO, SHIPDATE, EXPORTED, WSRECEIVING, DISRECEIVING,
	DMSCANNING, SENDERDESCRIPTION, LOCATIONID, LOCATIONAREAID, STAGEDSINCE, HASBEENCOPIED, VENDORCODE,
	CHANGED, DMPROCESSED, XDOCKTOUCHED, MANDATORYPRINTING)
  VALUES
    (SHIPMENT_LOGSQ.NEXTVAL, SYSTIMESTAMP, 'U',
	:OLD.SHIPMENTID, :OLD.CCODE_SENDER, :OLD.TMP, :OLD.LORRYID, :OLD.NRDOLLIES, :OLD.NRCRATES, :OLD.EXPECTED_DEPARTURE,
	:OLD.DEPARTURE, :OLD.EXPECTED_ARRIVAL, :OLD.ARRIVAL, :OLD.HASARRIVED, :OLD.HASBEENBOOKEDIN, :OLD.CLOSED,
	:OLD.CCODE_RECEIVER, :OLD.LICENSEPLATE, :OLD.SHIPMENTTYPE, :OLD.PRINTED, :OLD.CUSTNO, :OLD.SHIPDATE, :OLD.EXPORTED, :OLD.WSRECEIVING, :OLD.DISRECEIVING,
	:OLD.DMSCANNING, :OLD.SENDERDESCRIPTION, :OLD.LOCATIONID, :OLD.LOCATIONAREAID, :OLD.STAGEDSINCE, :OLD.HASBEENCOPIED, :OLD.VENDORCODE,
	:OLD.CHANGED, :OLD.DMPROCESSED, :OLD.XDOCKTOUCHED, :OLD.MANDATORYPRINTING);
END SHIPMENT_LOG2;
/
ALTER TRIGGER DISTRIB.SHIPMENT_LOG2 ENABLE;

-- ============================================================
-- TRIGGER 3: BEFORE DELETE
-- ============================================================
CREATE OR REPLACE TRIGGER DISTRIB.SHIPMENT_LOG3
  BEFORE DELETE ON DISTRIB.SHIPMENT
  FOR EACH ROW
BEGIN
  INSERT INTO SHIPMENT_LOG
    (ID, HAPPENED_AT, ACTION,
	SHIPMENTID, CCODE_SENDER, TMP, LORRYID, NRDOLLIES, NRCRATES, EXPECTED_DEPARTURE,
	DEPARTURE, EXPECTED_ARRIVAL, ARRIVAL, HASARRIVED, HASBEENBOOKEDIN, CLOSED,
	CCODE_RECEIVER, LICENSEPLATE, SHIPMENTTYPE, PRINTED, CUSTNO, SHIPDATE, EXPORTED, WSRECEIVING, DISRECEIVING,
	DMSCANNING, SENDERDESCRIPTION, LOCATIONID, LOCATIONAREAID, STAGEDSINCE, HASBEENCOPIED, VENDORCODE,
	CHANGED, DMPROCESSED, XDOCKTOUCHED, MANDATORYPRINTING)
  VALUES
    (SHIPMENT_LOGSQ.NEXTVAL, SYSTIMESTAMP, 'D',
	:OLD.SHIPMENTID, :OLD.CCODE_SENDER, :OLD.TMP, :OLD.LORRYID, :OLD.NRDOLLIES, :OLD.NRCRATES, :OLD.EXPECTED_DEPARTURE,
	:OLD.DEPARTURE, :OLD.EXPECTED_ARRIVAL, :OLD.ARRIVAL, :OLD.HASARRIVED, :OLD.HASBEENBOOKEDIN, :OLD.CLOSED,
	:OLD.CCODE_RECEIVER, :OLD.LICENSEPLATE, :OLD.SHIPMENTTYPE, :OLD.PRINTED, :OLD.CUSTNO, :OLD.SHIPDATE, :OLD.EXPORTED, :OLD.WSRECEIVING, :OLD.DISRECEIVING,
	:OLD.DMSCANNING, :OLD.SENDERDESCRIPTION, :OLD.LOCATIONID, :OLD.LOCATIONAREAID, :OLD.STAGEDSINCE, :OLD.HASBEENCOPIED, :OLD.VENDORCODE,
	:OLD.CHANGED, :OLD.DMPROCESSED, :OLD.XDOCKTOUCHED, :OLD.MANDATORYPRINTING);
END SHIPMENT_LOG3;
/
ALTER TRIGGER DISTRIB.SHIPMENT_LOG3 ENABLE;
